name: cipta_cuan
description: "CiptaCuan Version 1"
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.6
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.5.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/ciptacuan.png
  color: "#141231"
  android: true
  ios: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ciptacuan.png"
  adaptive_icon_foreground: "assets/ciptacuan.png"
  adaptive_icon_background: "#141231"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/category/
    - assets/images/no_data/
    - assets/onboarding/